#!/bin/sh
set -e

find /usr/lib/python2.7/dist-packages/plusrandr -type d -name __pycache__ -print0 | sudo xargs --null --no-run-if-empty rm -fr
rm -fr /usr/lib/python2.7/dist-packages/plusrandr/**.pyc
